name: 'Portfolio deployment'
on:
    push:
        branches:
            - 'master'

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [14.x]
        steps:
            - uses: actions/checkout@v2.3.1
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install Packages and Build
              run: |
                  npm install
                  npm run build
            - name: Deploy Application to GH Pages
              uses: JamesIves/github-pages-deploy-action@4.1.1
              with:
                  branch: gh-pages
                  folder: build
                  clean: true
                  token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
                  git-config-name: ${{ secrets.USERNAME }}
                  git-config-email: ${{ secrets.EMAIL }}
                  repository-name: ${{ secrets.REPO_NAME }}